language: cpp
os: linux
dist: bionic
compiler: gcc

jobs:
  include:
    - stage: "Application Build Test"

      before_install:
      - wget https://github.com/eXhumer/switch-ex-curl/releases/download/v7.69.1-3/switch-ex-curl-7.69.1-3-any.pkg.tar.zst
      - wget https://github.com/eXhumer/switch-ex-curl/releases/download/v7.69.1-3/switch-ex-curl-7.69.1-3-any.pkg.tar.zst.sig
      - wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb

      install:

      - sudo apt-get update && sudo apt-get install -y libarchive13
      - sudo dpkg --install devkitpro-pacman.amd64.deb
      - sudo dkp-pacman --sync --refresh --sysupgrade --noconfirm
      - sudo dkp-pacman --sync --noconfirm devkitA64 devkit-env libnx switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-freetype  switch-zlib switch-tools switch-bzip2
      - sudo dkp-pacman --upgrade --noconfirm switch-ex-curl-7.69.1-3-any.pkg.tar.zst

      before_script:
      - source /etc/profile.d/devkit-env.sh
      - export PATH=${DEVKITPRO}/portlibs/switch/bin:${PATH}

      script:
      - make

branches:
  only:
  - master
