name: GitHub Actions Atmosphere Updater CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  lib-build-test:
    name: Application Build Test

    runs-on: ubuntu-18.04
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Download switch-ex-curl
      run: |
        wget https://github.com/eXhumer/switch-ex-curl/releases/download/v7.69.1-3/switch-ex-curl-7.69.1-3-any.pkg.tar.zst
        wget https://github.com/eXhumer/switch-ex-curl/releases/download/v7.69.1-3/switch-ex-curl-7.69.1-3-any.pkg.tar.zst.sig

    - name: Install switch-ex-curl
      run: sudo dkp-pacman --upgrade --noconfirm switch-ex-curl-7.69.1-3-any.pkg.tar.zst

    - name: Install packages required for build from dkp-pacman
      run: sudo dkp-pacman --sync --noconfirm devkitA64 devkit-env libnx switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-freetype switch-zlib switch-tools switch-bzip2

    - name: Make application
      run: |
          source /etc/profile.d/devkit-env.sh
          export PATH=${PATH}:${DEVKITPRO}/portlibs/switch/bin
          make --directory=$GITHUB_WORKSPACE --file=$GITHUB_WORKSPACE/Makefile
