name: GitHub Actions Atmosphere Updater CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  lib-build-test:
    name: Application Build Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Download dkp-pacman
      run: wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb

    - name: Download switch-ex-curl
      run: wget https://github.com/eXhumer/switch-ex-curl/releases/download/v7.70.0/switch-ex-curl-7.70.0-1-any.pkg.tar.xz

    - name: Install dkp-pacman
      run: sudo dpkg --install devkitpro-pacman.deb

    - name: Update packages from dkp-pacman to latest
      run: sudo dkp-pacman --sync --refresh --sysupgrade --noconfirm

    - name: Install switch-ex-curl
      run: sudo dkp-pacman --upgrade --noconfirm switch-ex-curl-7.70.0-1-any.pkg.tar.xz

    - name: Install packages required for build from dkp-pacman
      run: sudo dkp-pacman --sync --noconfirm devkitA64 devkit-env libnx switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-freetype switch-zlib switch-tools switch-bzip2

    - name: Make application
      run: |
          source /etc/profile.d/devkit-env.sh
          export PATH=${PATH}:${DEVKITPRO}/portlibs/switch/bin
          make --directory=$GITHUB_WORKSPACE --file=$GITHUB_WORKSPACE/Makefile